### ISSUE TITLE
setup_repo_sicknetwork not found

### ISSUE THREAD

**Issue by rpSICK** [SICKAG/ScanSegmentDecoding#1]
Hello
The "setup_repo_sicknetwork.bat" file is not in the repo.
Is it still necessary to work inside the SICK network?

Thank you
Rotem

**Comment by weinmalSICKAG** [comment]
Hello Rotem,
setup_repo_sicknetwork.bat is not necessary anymore to work inside the SICK network. This is a mistake in the documentation. This will be corrected in the next release.

**Comment by rpSICK** [comment]
Thank you!
